// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIb7HmWTVMmn81mziB4d1nT7uR7sVRHbo',
    appId: '1:86050057399:web:eaf818b271581c141df132',
    messagingSenderId: '86050057399',
    projectId: 'chat-app-fe596',
    authDomain: 'chat-app-fe596.firebaseapp.com',
    storageBucket: 'chat-app-fe596.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB53xyLGwhvmXQzccliutd8tgm1BG8wQ',
    appId: '1:86050057399:android:d6b1736334e8167b1df132',
    messagingSenderId: '86050057399',
    projectId: 'chat-app-fe596',
    storageBucket: 'chat-app-fe596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ZInzjF1W3BHDs-53-3D5sMNEhRS6qBQ',
    appId: '1:86050057399:ios:622b3c05ca0121fd1df132',
    messagingSenderId: '86050057399',
    projectId: 'chat-app-fe596',
    storageBucket: 'chat-app-fe596.appspot.com',
    iosClientId: '86050057399-dm9cop3tr870ud42lv136p8o3lcuovkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ZInzjF1W3BHDs-53-3D5sMNEhRS6qBQ',
    appId: '1:86050057399:ios:622b3c05ca0121fd1df132',
    messagingSenderId: '86050057399',
    projectId: 'chat-app-fe596',
    storageBucket: 'chat-app-fe596.appspot.com',
    iosClientId: '86050057399-dm9cop3tr870ud42lv136p8o3lcuovkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
